### ISSUE TITLE
Review Tugas 1

### ISSUE THREAD

**Issue by herripurba** [cg2021a/tugas-1-putukrisna6#1]
Benda yang anda berikan terlalu persegi dan tidak ada kurva sehingga ini termasuk penilaian dengan kategori mudah. Jika ingin diganti harap memberitahu asisten agar dapat di review lagi dan jika tetap ingin menggunakan gambar ini tidak apa-apa

**Comment by putukrisna6** [comment]
@herripurba 
terima kasih atas review nya mas. Saya sudah coba mengganti benda yang diberikan, jika sempat mohon di-review kembali ya, mas.

**Comment by herripurba** [comment]
itu dah termasuk ke kategory sulit kalau yakin mau ngambar itu gakapa2 tapi kalau mau diubah lg blang
